config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  # Attributes
  # name: string
  # age: integer
  # cuteness: integer
  # softness: integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_flickr, only: %i[index show new]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: 'Kitten was successfully created.'
    else
      render 'new', alert: 'Kitten was not created.'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten was successfully updated.'
    else
      render 'edit', alert: 'Kitten was not updated.'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to kittens_path, notice: 'Kitten was successfully destroyed.'
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_flickr
    p key = ENV.fetch('FLICKR_API_KEY')
    p secret = ENV.fetch('FLICKR_SHARED_SECRET')
    @flickr = Flickr.new(key, secret)
    @photos = @flickr.photos.search(profile: true, user_id: '197231518@N07')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten, local: true) do |form| %>
  <div class="columns">
    <div class="column">
      <div class="field">
        <div class="card">
          <div class="card-image">
            <% photo = @photos.to_a.sample %>
            <%= image_tag @flickr.photos.getSizes(photo_id: photo.id).to_a.last.source %>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class: "input" %>
      </div>
      <div class="field">
        <%= form.label :age %>
        <%= form.number_field :age, class: "input" %>
      </div>
      <div class="field">
        <%= form.label :cuteness %>
        <%= form.number_field :cuteness, class: "input" %>
      </div>
      <div class="field">
        <%= form.label :softness %>
        <%= form.number_field :softness, class: "input" %>
      </div>
      <div class="actions">
        <%= form.submit button_text, class: "button is-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<h1 class="title is-1 has-text-centered"><%= kitten.name %>'s profile</h1>
<br>
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      Personal Details
    </p>
  </header>
  <div class="columns">
    <div class="column is-5">
      <div class="card-image py-5">
        <figure class="image">
          <% photo = @photos.to_a[kitten.id % photos.to_a.length] %>
          <%= image_tag @flickr.photos.getSizes(photo_id: photo.id).to_a.last.source %>
        </figure>
      </div>
    </div>
    <div class="column is-5">
      <div class="card-content">
        <div class="content">
          <p>
            <strong>Age:</strong> <%= kitten.age %> Years
          </p>
          <br>
          <p class="title is-4">Cuteness:</p>
          <progress class="progress is-success" value="<%= kitten.cuteness %>" max="10"></progress>
          <br>
          <p class="title is-4">Softness:</p>
          <progress class="progress is-info" value="<%= kitten.softness %>" max="10"></progress>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/kittens/edit.html.erb
<div class="box">
  <h1 class="title">Edit <%= @kitten.name %></h1>
  <%= render 'form', kitten: @kitten, button_text: "Update Kitten" %>
</div>

app/views/kittens/index.html.erb
<div class="box p-6">
  <%= link_to 'New Kitten', new_kitten_path, class: 'button is-primary' %>
  <br>
  <hr>
  <% if @kittens.empty? %>
    <div class="content">
      <p class="has-text-centered has-text-grey-light is-size-4 has-text-weight-semibold">
        No kittens found.
      </p>
    </div>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Age</th>
          <th>Cuteness</th>
          <th>Softness</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @kittens.each do |kitten| %>
          <tr>
            <td><%= kitten.id %></td>
            <td><%= kitten.name %></td>
            <td><%= kitten.age %></td>
            <td><%= kitten.cuteness %></td>
            <td><%= kitten.softness %></td>
            <td>
              <div class="buttons">
                <%= link_to 'Show', kitten_path(kitten), class: 'button is-success is-outlined is-small' %>
                <%= link_to 'Edit', edit_kitten_path(kitten), class: 'button is-info is-outlined is-small' %>
                <%= button_to 'Delete', kitten_path(kitten), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger is-outlined is-small' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
</div>

app/views/kittens/new.html.erb
<div class="box">
  <h1 class="title">New Kitten</h1>
  <%= render 'form', kitten: @kitten, button_text: "Create Kitten", photos: @photos, flickr: @flickr %>
</div>

app/views/kittens/show.html.erb
<%= render 'kitten', kitten: @kitten, photos: @photos, flickr: @flickr %>
<br>
<div class="buttons is-centered">
  <button class="button is-info" onclick="window.location.href='<%= edit_kitten_path(@kitten) %>'">Edit</button>
  <%= button_to 'Delete', kitten_path(@kitten), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %>
  <a class="button is-primary" href="<%= kittens_path %>">Back</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-three-quarters">
          <div class="content py-6">
            <% if notice %>
              <div class="notification is-success">
                <button class="delete"></button>
                <%= notice %>
              </div>
            <% end %>
            <% if alert %>
              <div class="notification is-danger">
                <button class="delete"></button>
                <%= alert %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>